controller:
  ## Container Settigns
  image: "jenkins/jenkins"
  tag: latest
  
  ## Resource Settings
  resources:
    requests:
      cpu: ".5"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "1Gi"
 
  ## Java Settings
  javaOpts: "-Duser.timezone=America/New_York"
  
  ## Service Settings
  serviceType: LoadBalancer
  servicePort: 80
  
  ## Plugin Settings
  installLatestPlugins: true
  overwritePlugins: true
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - job-dsl
    - github-oauth
    - credentials-binding
    - blueocean
  
  ## Configuration Secrets settings
  containerEnv:
  - name: SECRETS
    value: /jcasc/secrets

  ## Configuration as Code
  JCasC:
    enabled: true
    defaultConfig: true
    securityRealm: github
    configScripts:
    
      ## Use Github to log in
      security: |
        jenkins:
          securityRealm:
            github:            
              clientID: ${GITHUB_CLIENT_ID}
              clientSecret: ${GITHUB_CLIENT_SECRET}
              githubWebUri: "https://github.com"
              githubApiUri: "https://api.github.com"
              oauthScopes: "read:org,user:email,repo"    
              
      ## default Job Settings
      jobs: |
        jobs:
        - script: >
            pipelineJob('Scripted-pipeline') {
              definition {
                cpsScm {
                  scm {
                    git {
                      remote {
                         url('https://github.com/mount986/jenkins-demo.git')
                      }
                      branch('*/main')
                    }
                  }
                  lightweight()
                  scriptPath('Jenkinsfile')      
                }
              }
            }            
                  
  ## Auto-reload configuration changes
  sidecars:
    configAutoReload:
      enabled: true
  
## Default Agent Settings (can be overwritten in the Jenkinsfile)
agent:
  enabled: true
  image: "jenkins/inbound-agent"
  resources:
    requests:
      cpu: "0.5"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "2Gi"
  # You may want to change this to true while testing a new image
  alwaysPullImage: true
  
## Configuration Volumes Settings
persistence:
  
  ## Use the PVC from storage.yaml to persist configurations
  enabled: true
  existingClaim: jenkins-config-pvc
  
  ## The mount/volume for storing Configuration Secrets 
  mounts:
  - name: jcasc-secrets
    mountPath: /jcasc/secrets
  volumes:
  - name: jcasc-secrets
    secret:
      secretName: jenkins-config-secret

## Install Default RBAC roles and bindings (needed for auto-config reloading)
rbac:
  create: true

serviceAccount:
  create: true

